export RAVE_TRACE_SCALAR=0
export RAVE_PRINT_REPORT=1
export RAVE_VLEN=16384

export RAVE_TRACE_EXTENDED=0
export RAVE_RAW_DIST=0
export RAVE_WAR_DIST=0
export RAVE_WAW_DIST=0
export RAVE_DEBUG_INFO=0
